name: metaozce
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  curved_navigation_bar: ^1.0.3
  flutter:
    sdk: flutter
  flutter_signin_button: ^2.0.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.2.1
  flutter_bloc: ^8.0.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/